### ISSUE TITLE
'event-slot' returns 'air'

### ISSUE THREAD

**Issue by TrademarkTM** [bensku/Skript#362]
I've been trying to block some slots in Skript, but the 'event-slot' always returns 'air' for some reason instead of the clicked slot.

**Skript version**: dev23
**Server version**: 1.11.2

http://prntscr.com/e0o4lu

**Comment by Shane1199** [comment]
I've noticed this too in other versions as well.

**Comment by TheBentoBox** [comment]
Yeah, can't seem to get the slot either in my testing, even though `event-slot` is a valid expression. Note `event-item` DOES work to get the item that's in the clicked slot at the time of the click.

**Comment by bensku** [comment]
Did it work with 1.10?

**Comment by FUZIK** [comment]
gif: [drive.google.com/open?id=0BwoHMFwec-qHMnRTc0QxSk1KN1E](url) 10MB!
slot.sk:
```
on inventory click:
	event-slot != air
	broadcast colored "%event-slot% |%random number between 1 and 3%|" # "random" for illustration
```

**Comment by Shane1199** [comment]
event-block does the same

**Comment by Pyon-Pyon** [comment]
@Shane1199 there isn't an event-block in the inventory click event so I don't know of what you're talking about.

**Comment by bensku** [comment]
Are you possibly testing this in creative gamemode? Bukkit inventory events fire differently there, and so are not supported by Skript.

**Comment by TrademarkTM** [comment]
Tested it better:
**Creative:** the inventory click doesn't fire if you click the item list in creative. But when you click your own inventory in creative, event-slot returns the item in that slot.
**Survival:** no matter what, it returns 'air'.
**Adventure:** same thing as survival.

**Other inventories:** returns the item currently in that slot.

**Comment by TheLimeGlass** [comment]
Isn't this a Spigot feature? Mojang or Spigot made it so that when you click a slot and there is nothing in it, it returns air. It returns null or "nothing" if they click outside of the inventory. Such as in a place that ahs no slots. I don't think this is a bug but rather an important feature to determine the difference between an inventory click and a click around the inventory.

**Comment by TheBentoBox** [comment]
The issue being reported was that the expression was always returning air, even in situations where the slot wasn't empty. I agree that it should air as opposed to null if an empty slot is clicked. However, this issue is almost a year old, so it very well may have been fixed by now through some tangential issue. If anyone wants to test it for me on the latest release that'd be very helpful. Without **any** addons, too, as a large number of addons extend upon or add their own inventory events which could cause issues.

**Comment by Snow-Pyon** [comment]
Could someone confirm this is still an issue?

**Comment by TrademarkTM** [comment]
Here: https://i.imgur.com/3bqDKOA.png
Using only skQuery.

Skript dev34, skQuery 3.6.0.
Event-slot should return a number, shouldn't it?

(tested now without skquery and it still happens)

**Comment by bensku** [comment]
Slot is not a number. It has a number, but also can be used in place of an item.

**Comment by subarucantdie01** [comment]
> gif: [drive.google.com/open?id=0BwoHMFwec-qHMnRTc0QxSk1KN1E](url) 10MB! slot.sk:
> 
> ```
> on inventory click:
> 	event-slot != air
> 	broadcast colored "%event-slot% |%random number between 1 and 3%|" # "random" for illustration
> ```

you should use colored for the checks, also if you wanna make it an illustration use "&%random number between 1 and 3%%event-slot%"

**Comment by subarucantdie01** [comment]
> > gif: [drive.google.com/open?id=0BwoHMFwec-qHMnRTc0QxSk1KN1E](url) 10MB! slot.sk:
> > ```
> > on inventory click:
> > 	event-slot != air
> > 	broadcast colored "%event-slot% |%random number between 1 and 3%|" # "random" for illustration
> > ```
> 
> you should use colored for the checks, also if you wanna make it an illustration use "&%random integer between 1 and 3%%event-slot%"

random number gives double / float, but if it is integer then it gives the number 1, 2 or 3 at the time

**Comment by AyhamAl-Ali** [comment]
No need to bump an old resolved issue.
